# Stage 1: Base image for runtime
FROM nginx AS base
EXPOSE 80
EXPOSE 8080

# Stage 2: Build environment
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["BlazorApp1.csproj", "."]
RUN dotnet restore "BlazorApp1.csproj"


COPY . .
WORKDIR "/src"
RUN dotnet build "BlazorApp1.csproj" -c Release -o /app/build

# Stage 3: Publish
FROM build AS publish
RUN dotnet publish "BlazorApp1.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 4: Final image
FROM base AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
# COPY nginx.conf /etc/nginx/nginx.conf

